const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem('abToken')||'', state={devices:[]}, selectedId=localStorage.getItem('abDevice')||'', view='overview';

async function api(path,opt={}){
  const headers={'Content-Type':'application/json',...(opt.headers||{})}; if(token)headers.Authorization='Bearer '+token;
  const r=await fetch(path,{...opt,headers,cache:'no-store'}); const j=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(j.error||('HTTP '+r.status)); return j;
}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function js(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
function key(s){return btoa(unescape(encodeURIComponent(s))).replace(/[^a-zA-Z0-9]/g,'')}
function dev(){return state.devices.find(d=>d.id===selectedId)||state.devices[0]||null}
function age(ts){if(!ts)return 'Never';let s=Math.max(0,Math.floor(Date.now()/1000-ts));if(s<60)return s+' sec ago';if(s<3600)return Math.floor(s/60)+' min ago';if(s<86400)return Math.floor(s/3600)+' hr ago';return Math.floor(s/86400)+' d ago'}
function parseThreshold(v){try{return typeof v==='string'?JSON.parse(v):v||[15,10,5,1]}catch{return[15,10,5,1]}}
function protectionMap(d){let t=new Set(d?.tamper||[]);return {accessibility:!t.has('Accessibility service is disabled'),usage:!t.has('Usage access is missing')}}

async function login(){const p=$('#password').value;$('#loginErr').textContent='';try{let r=await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:p})});token=r.token;localStorage.setItem('abToken',token);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load()}catch(e){$('#loginErr').textContent=e.message==='invalid credentials'?'Incorrect password.':e.message}}
async function load(preserveScroll=false){const y=window.scrollY;state=await api('/api/admin/state');if(!selectedId||!state.devices.some(d=>d.id===selectedId))selectedId=state.devices[0]?.id||'';localStorage.setItem('abDevice',selectedId);renderDevicePicker();render();if(preserveScroll)requestAnimationFrame(()=>window.scrollTo(0,y))}
function renderDevicePicker(){let s=$('#deviceSelect');s.innerHTML=state.devices.length?state.devices.map(d=>`<option value="${esc(d.id)}" ${d.id===selectedId?'selected':''}>${esc(d.name||d.model||'Android device')}</option>`).join(''):'<option>No devices</option>';s.disabled=!state.devices.length;let d=dev();let hp=$('#headerStatus');if(!d){hp.textContent='No device';hp.className='statusPill';return}let online=Date.now()/1000-(d.last_seen||0)<90;hp.textContent=online?'Online':'Last seen '+age(d.last_seen);hp.className='statusPill '+(online?'good':'bad')}
function render(){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));let c=$('#content');({overview:renderOverview,apps:renderApps,protection:renderProtection,settings:renderSettings,pair:renderPair}[view]||renderOverview)(c)}
function noDevice(c,title){c.innerHTML=`<div class="pageTitle"><div><h1>${title}</h1><p class="muted">Pair a device to continue.</p></div></div><div class="empty">No paired devices yet.</div>`}

function renderOverview(c){let d=dev();if(!d)return noDevice(c,'Overview');let p=protectionMap(d), blocked=d.apps.filter(a=>a.mode==='BLOCKED').length, limited=d.apps.filter(a=>a.mode==='TIME_LIMITED').length, userApps=d.apps.filter(a=>!a.system_app).length;c.innerHTML=`
<div class="pageTitle"><div><h1>${esc(d.name)}</h1><p class="muted">${esc(d.manufacturer)} ${esc(d.model)} · Android ${esc(d.android_version)}</p></div><span class="pill ${d.protection_status==='healthy'?'good':'warn'}">${esc(d.protection_status||'unknown')}</span></div>
<div class="panel deviceHero"><div><div class="eyebrow">Device name</div><div class="deviceNameEdit"><input id="deviceName" maxlength="80" value="${esc(d.name)}"><button class="primary" onclick="renameDevice()">Save name</button></div></div><div class="smallText">ID: ${esc(d.id.slice(0,8))}…<br>Last sync: ${age(d.last_seen)}</div></div>
<div class="grid"><div class="statCard"><div class="statLabel">User applications</div><div class="statValue">${userApps}</div></div><div class="statCard"><div class="statLabel">Always blocked</div><div class="statValue">${blocked}</div></div><div class="statCard"><div class="statLabel">Time limited</div><div class="statValue">${limited}</div></div><div class="statCard"><div class="statLabel">Protection</div><div class="statValue">${[p.accessibility,p.usage,p.admin].filter(Boolean).length}/3</div></div></div>
<div class="panel"><h3>Protection snapshot</h3><div class="protectionList">${protRow('Accessibility',p.accessibility)}${protRow('Usage access',p.usage)}</div></div>`}
function protRow(name,ok){return `<div class="protectionItem"><span>${name}</span><span class="pill ${ok?'good':'bad'}">${ok?'Active':'Needs attention'}</span></div>`}
async function renameDevice(){let name=$('#deviceName').value.trim();if(!name)return;await api('/api/admin/device/rename',{method:'POST',body:JSON.stringify({device_id:dev().id,name})});await load(true)}

function renderApps(c){let d=dev();if(!d)return noDevice(c,'Applications');c.innerHTML=`<div class="pageTitle"><div><h1>Applications</h1><p class="muted">Policies for ${esc(d.name)} only.</p></div></div><div class="panel"><div class="toolbar"><input id="appSearch" class="search" placeholder="Search app or package"><label class="switch"><input id="showSystem" type="checkbox"> Show system apps</label></div><div id="appList" class="appList"></div></div>`;$('#appSearch').oninput=renderAppRows;$('#showSystem').onchange=renderAppRows;renderAppRows()}
function renderAppRows(){let d=dev(),q=($('#appSearch')?.value||'').toLowerCase(),showSystem=$('#showSystem')?.checked;let usage=Object.fromEntries((d.usage||[]).map(x=>[x.package_name,x.seconds]));let apps=d.apps.filter(a=>(showSystem||!a.system_app)&&(!q||a.app_name.toLowerCase().includes(q)||a.package_name.toLowerCase().includes(q)));let el=$('#appList');if(!apps.length){el.innerHTML='<div class="empty">No applications match this filter.</div>';return}el.innerHTML=apps.map(a=>{let k=key(a.package_name),used=Math.floor((usage[a.package_name]||0)/60);return `<div class="appRow" id="row_${k}"><div class="appIdentity">${a.icon_b64?`<img class="appIcon" src="data:image/png;base64,${a.icon_b64}">`:'<div class="appIcon"></div>'}<div><div class="appName">${esc(a.app_name)}</div><div class="package">${esc(a.package_name)}${a.system_app?' · system':''}</div></div></div><select id="mode_${k}" onchange="modeChange('${js(a.package_name)}',this.value)"><option value="UNRESTRICTED" ${a.mode==='UNRESTRICTED'?'selected':''}>Allowed</option><option value="BLOCKED" ${a.mode==='BLOCKED'?'selected':''}>Blocked</option><option value="TIME_LIMITED" ${a.mode==='TIME_LIMITED'?'selected':''}>Time limit</option></select><div class="limits" id="limits_${k}">${limitControls(a)}</div><div class="metric">${used} min / 24h</div></div>`}).join('')}
function limitControls(a){if(a.mode!=='TIME_LIMITED')return '<span class="smallText">No time limit</span>';let k=key(a.package_name),mins=a.window_minutes||60,unit=mins%1440===0?1440:(mins%60===0?60:1),shown=mins/unit;return `<input id="allow_${k}" type="number" min="1" value="${a.allowance_minutes||10}"><span class="smallText">min every</span><input id="window_${k}" type="number" min="1" value="${shown}"><select id="unit_${k}"><option value="1" ${unit===1?'selected':''}>min</option><option value="60" ${unit===60?'selected':''}>hours</option><option value="1440" ${unit===1440?'selected':''}>days</option></select><button class="primary" onclick="saveLimit('${js(a.package_name)}')">Save</button>`}
async function modeChange(pkg,mode){let d=dev(),a=d.apps.find(x=>x.package_name===pkg),k=key(pkg);a.mode=mode;if(mode==='TIME_LIMITED'){a.allowance_minutes=a.allowance_minutes||10;a.window_minutes=a.window_minutes||60}$('#limits_'+k).innerHTML=limitControls(a);try{await api('/api/admin/policy',{method:'POST',body:JSON.stringify({device_id:d.id,package_name:pkg,mode,allowance_minutes:mode==='TIME_LIMITED'?a.allowance_minutes:null,window_minutes:mode==='TIME_LIMITED'?a.window_minutes:null,window_anchor:'FIXED'})})}catch(e){alert(e.message);await load(true)}}
async function saveLimit(pkg){let k=key(pkg),a=+$(`#allow_${k}`).value,w=+$(`#window_${k}`).value,u=+$(`#unit_${k}`).value,minutes=Math.round(w*u);if(a<1||minutes<1||a>minutes){alert('The allowed time must be between 1 minute and the selected window.');return}try{await api('/api/admin/policy',{method:'POST',body:JSON.stringify({device_id:dev().id,package_name:pkg,mode:'TIME_LIMITED',allowance_minutes:Math.round(a),window_minutes:minutes,window_anchor:'FIXED'})});let app=dev().apps.find(x=>x.package_name===pkg);app.allowance_minutes=Math.round(a);app.window_minutes=minutes;let b=$(`#limits_${k} .primary`);if(b){let old=b.textContent;b.textContent='Saved';setTimeout(()=>b.textContent=old,900)}}catch(e){alert(e.message)}}

function renderProtection(c){let d=dev();if(!d)return noDevice(c,'Protection');let p=protectionMap(d);c.innerHTML=`<div class="pageTitle"><div><h1>Protection</h1><p class="muted">Runtime status for ${esc(d.name)}.</p></div></div><div class="panel"><div class="protectionList">${protRow('Accessibility service',p.accessibility)}${protRow('Usage access',p.usage)}</div></div><div class="panel"><h3>Attention log</h3>${d.tamper?.length?d.tamper.map(x=>`<div class="notice warn">${esc(x)}</div>`).join(''):'<div class="notice">No runtime issues reported by the device.</div>'}</div>`}
function renderSettings(c){let d=dev();if(!d)return noDevice(c,'Settings');let s=d.settings||{};c.innerHTML=`<div class="pageTitle"><div><h1>Device settings</h1><p class="muted">Settings below apply only to ${esc(d.name)}.</p></div></div><div class="settingsGrid"><div class="panel"><h3>General block image</h3>${s.general_image?`<img class="preview" src="${esc(s.general_image)}?v=${Date.now()}">`:'<div class="preview"></div>'}<input type="file" accept="image/*" onchange="uploadImage('general',this)"></div><div class="panel"><h3>Time-limit image</h3>${s.time_image?`<img class="preview" src="${esc(s.time_image)}?v=${Date.now()}">`:'<div class="preview"></div>'}<input type="file" accept="image/*" onchange="uploadImage('time',this)"></div></div><div class="panel"><h3>Time-limit notifications</h3><p class="muted">Minutes remaining before the limit is reached.</p><div class="formRow"><input id="thresholds" value="${esc(parseThreshold(s.notification_thresholds).join(', '))}"><button class="primary" onclick="saveThresholds()">Save</button></div></div>`}
async function uploadImage(kind,input){let f=input.files[0];if(!f)return;let r=new FileReader;r.onload=async()=>{try{await api('/api/admin/image',{method:'POST',body:JSON.stringify({device_id:dev().id,kind,data_url:r.result})});await load(true)}catch(e){alert(e.message)}};r.readAsDataURL(f)}
async function saveThresholds(){let a=$('#thresholds').value.split(',').map(x=>Number(x.trim())).filter(Number.isInteger);try{await api('/api/admin/settings',{method:'POST',body:JSON.stringify({device_id:dev().id,notification_thresholds:a})});alert('Notification thresholds saved.')}catch(e){alert(e.message)}}
function renderPair(c){c.innerHTML=`<div class="pageTitle"><div><h1>Pair a device</h1><p class="muted">Connect another Android phone to this server.</p></div></div><div class="panel"><div class="notice">On the phone, open the device management app, enter this computer's server address, create a pairing code, then enter that code below.</div><label>Pairing code</label><div class="formRow"><input id="pairCode" class="pairCode" placeholder="ABCD-EFGH" maxlength="9"><button class="primary" onclick="approvePair()">Approve device</button></div><div id="pairMsg" class="smallText"></div></div>`}
async function approvePair(){let msg=$('#pairMsg');try{let r=await api('/api/admin/pair/approve',{method:'POST',body:JSON.stringify({code:$('#pairCode').value})});msg.textContent='Device approved.';selectedId=r.device_id;setTimeout(load,700)}catch(e){msg.textContent=e.message}}

$('#loginBtn').onclick=login;$('#password').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login()}});$('#togglePassword').onclick=()=>{let p=$('#password');p.type=p.type==='password'?'text':'password';$('#togglePassword').textContent=p.type==='password'?'Show':'Hide';p.focus()};$('#refresh').onclick=()=>load(true);$('#deviceSelect').onchange=e=>{selectedId=e.target.value;localStorage.setItem('abDevice',selectedId);renderDevicePicker();render()};$$('.nav').forEach(n=>n.onclick=()=>{view=n.dataset.view;render()});
if(token)load().then(()=>{$('#login').classList.add('hidden');$('#app').classList.remove('hidden')}).catch(()=>{token='';localStorage.removeItem('abToken')});
